# set docker compose version
version: "3"
# build services
services:
  web:
    env_file: env.list
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/spender_prod
    image: "superbikezacc/spender:latest"
    depends_on:
      - db
    ports:
      - "5002:5002"
  db:
    env_file: db.list
    image: postgres:10.3
