version: '3'
web:
  image: superbikezacc/spender:spender_staging
  environment:
      - DATABASE_URL=ecto://postgres:postgres@db/spender_prod
  env_file:
    - web.env
  command: env
  ports:
    - "5001:5001"
db:
  image: postgres:latest
  ports:
    - "5432:5432"
  volumes:
    - mula-staging:/var/lib/postgresql

volumes:
  mula-staging:
    external: true
