# set docker compose version
version: "3"
# build services
services:
  web:
    image: superbikezacc/spender:production
    ports:
      - "5005:5005"
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/spender_prod
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - mula-staging:/var/lib/postgresql

volumes:
  mula-data:
    external: true # use a preexisting external data volume
  mula-staging:
    external: true
