# set docker compose version
version: "3"
# build services
services:
  web:
    env_file: env.list
    environment:
      - DATABASE_URL=ecto://postgres:postgres@db/spender_prod
    depends_on:
      - db
  db:
    env_file: db.list
    image: postgres:latest
    ports:
      - "5432:5432"

volumes:
  mula-data:
    external: true # use a preexisting external data volume
