version: 2
jobs:
  build:
    working_directory: /spender
    docker:
      - image: bitwalker/alpine-elixir-phoenix
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - run:
          name: Get Dependecies
          command: mix deps.get
      - run:
          name: Compile
          command: mix compile
      - persist_to_workspace:
          root: /
          paths: .
  test:
    docker:
      - image: bitwalker/alpine-elixir-phoenix
        environment:
          MIX_ENV: test
    steps:
      - attach_workspace:
          at: /spender
      - run:
        name: Run Tests
        comand: mix test

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
